export const MARKS = {
  "Hyundai": ["H1", "Santa Fe", "Terracan", "Tucson"],
  "Jeep": ["Cherokee", "Grand Cherokee", "Wrangler"],
  "Kia": ["Sorento", "Sportage"],
  "Mitsubishi": ["L200","L300", "Pajero", "Pajero Sport"],
  "BMW": ["X5"],
  "Chevrolet": ["Tahoe", "Blazer"],
  "Ford": ["Explorer", "F-150", "F-250", "Maverick", "Ranger", "Transit"],
  "Honda": ["CR-V"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Sport"],
  "Mazda": ["B-Fighter", "B2500", "BT"],
  "Mercedes-Benz": ["Sprinter", "Vito", "ML", "G"],
  "Nissan": ["Navara", "Pathfinder", "Patrol", "Qashqai", "Terrano", "X-Trail"],
  "Opel": ["Frontera", "Vivaro"],
  "Renault": ["Trafic", "Master"],
  "Subaru": ["Forester"],
  "Suzuki": ["Grand Vitara", "Jimny", "Vitara"],
  "Toyota": ["4-Runner", "Highlander", "Hilux", "Land Cruiser", "RAV4", "Sequoia", "Tundra"],
  "Volkswagen": ["Amarok", "Crafter", "LT", "Sharan", "T3", "T4", "T5", "T6", "Tiguan", "Touareg"],
  "Volvo": ["XC60", "XC90"],
}
export const CAR_EMPTY = {
  id: "",
  marka: "",
  model: "",
  priceNum: "",
  priceCurrency: "",
  hasTO: "",
  year: "",
  mileage: "",
  engineVolume: "",
  bodyNotes: "",
  images: [],
}
