export const MARKS = {
  "Hyundai": ["H1", "Santa Fe", "Terracan", "Tucson"],
  "Jeep": ["Cherokee", "Grand Cherokee", "Wrangler"],
  "Kia": ["Sorento", "Sportage"],
  "Mitsubishi": ["L200","L300", "Pajero", "Pajero Sport"],
  "BMW": ["X5"],
  "Chevrolet": ["Tahoe", "Blazer"],
  "Ford": ["Explorer", "F-150", "F-250", "Maverick", "Ranger", "Transit"],
  "Honda": ["CR-V"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Sport"],
  "Mazda": ["B-Fighter", "B2500", "BT"],
  "Mercedes-Benz": ["Sprinter", "Vito", "ML", "G"],
  "Nissan": ["Navara", "Pathfinder", "Patrol", "Qashqai", "Terrano", "X-Trail"],
  "Opel": ["Frontera", "Vivaro"],
  "Renault": ["Trafic", "Master"],
  "Subaru": ["Forester"],
  "Suzuki": ["Grand Vitara", "Jimny", "Vitara"],
  "Toyota": ["4-Runner", "Highlander", "Hilux", "Land Cruiser", "RAV4", "Sequoia", "Tundra"],
  "Volkswagen": ["Amarok", "Crafter", "LT", "Sharan", "T3", "T4", "T5", "T6", "Tiguan", "Touareg"],
  "Volvo": ["XC60", "XC90"],
}
export const CAR_EMPTY = {
  id: "",
  marka: "",
  model: "",
  name: "",
  priceNum: "",
  priceCurrency: "",
  price: "",
  year: "",
  mileage: "",
  engineVolume: "",
  transmission: "",
  gear: "",
  isTO: false,
  isVin: false,
  innerSmell: "",
  climat: "",
  light: "",
  salonResult: "",
  obd: "",
  bodyNotes: "",
  bodyInnerNotes: "",
  fullFront: "",
  fullCenter: "",
  fullRear: "",
  kpp: "",
  gyr: "",
  breakFront: "",
  breakRear: "",
  bodyTechnicNotes: "",
  clutch: "",
  acceleration: "",
  brake: "",
  vibrationSpeed: "",
  isMkppError: false,
  isErrorMkppSelector: false,
  isErrorMkppSynkro: false,
  isErrorMkppKnocksOut: false,
  isErrorMkppVibration: false,
  isAkppError: false,
  isErrorAkppSelector: false,
  isErrorAkppSynkro: false,
  isErrorAkppVibration: false,
  helmZero: "",
  helmTurn: "",
  helmBacklash: "",
  fullDrive: "",
  fullDriveBacklash: "",
  suspension: "",
  oilSmell: "",
  driveNotes: "",
  emulsion: "",
  coolantFluid: "",
  grm: "",
  turbo: "",
  fuelSystem: "",
  guessEngine: "",
  radiator: "",
  engineColdNotes: "",
  smokeEngine: "",
  bubblesInCool: "",
  secondStart: "",
  engineHotNotes: "",
  startTemp: "",
  noiseEngine: "",
  noiseGyr: "",
  engineStartNotes: "",
  otherNotes: "",
  chassis: "",
  imgBody: [],
  imgBodyStrong: [],
  imgBodyGear: [],
  imgBodyInner: [],
  imgBodyShrus: [],
  imgBodyGyr: [],
  imgTurbo: [],
  imgFuelSystem: [],
  imgGuessEngine: [],
  imgRadiator: [],
  imgSmokeEngine: [],
  imgFirstStart: [],
  imgOther: [],
}
